[project]
name = "tcc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.54.0",
    "qdrant-client>=1.14.3",
    "sentence-transformers>=4.1.0",
    "streamlit>=1.46.0",
]